$('.owl-carousel').owlCarousel({
  loop:true,
  margin:0,
  nav:false,
  autoplay:true,
  autoplayTimeout:5000,
  animateOut: 'fadeOut',
    responsive:{
      0:{
        items:1
      },
      600:{
        items:1
      },
      1000:{
        items:1
      }
    }
  })
$(document).ready(function(){
    $('.venobox').venobox(); 
});